/**
 * Textes d'interface propres aux pages de classement. Les traductions hors français et anglais
 * sont des brouillons produits pour l'aperçu ; elles ne sont pas approuvées pour l'indexation.
 *
 * Ordre des champs dans chaque ligne : hubTitle, hubDescription, hubIntroduction, openRanking,
 * emptyHub, rankings, week, rankedEntries, publishedEditions, updated, availableLanguages, rank,
 * name, score, movement, source, profile, limitations, evidence, methodology, newEntry,
 * sourceRepository, sourcePublisher, sourceIndependentTest, sourceBenchmark, sourceEditorial.
 */
const MESSAGE_KEYS = [
  'hubTitle',
  'hubDescription',
  'hubIntroduction',
  'openRanking',
  'emptyHub',
  'rankings',
  'week',
  'rankedEntries',
  'publishedEditions',
  'updated',
  'availableLanguages',
  'rank',
  'name',
  'score',
  'movement',
  'source',
  'profile',
  'limitations',
  'evidence',
  'methodology',
  'newEntry',
  'sourceRepository',
  'sourcePublisher',
  'sourceIndependentTest',
  'sourceBenchmark',
  'sourceEditorial',
] as const;

type RankingMessageKey = (typeof MESSAGE_KEYS)[number];
type RankingMessageValues = Record<RankingMessageKey, string>;

// Rows use a visible separator so translations stay compact while their field order is testable.
const TRANSLATIONS = {
  en: 'AI rankings¦Dated, sourced AI rankings built with published methods.¦Explore dated rankings with their candidates, sources and published methods.¦Open ranking →¦No localized ranking edition is ready yet. Reviewed collections will appear after their data is published.¦AI rankings¦Week¦{{count}} ranked entries¦{{count}} published editions¦Updated:¦Also available in¦Rank¦Name¦Score¦Movement¦Source¦Profile¦Limitations¦Evidence ({{count}})¦Methodology and limitations¦NEW¦Repository¦Publisher¦Independent test¦Benchmark¦Editorial',
  fr: 'Classements IA¦Des classements IA datés et sourcés, calculés selon des méthodes publiées.¦Explorez des classements datés avec leurs candidats, leurs sources et leurs méthodes publiées.¦Ouvrir le classement →¦Aucune édition localisée n’est encore prête. Les classements relus apparaîtront après publication de leurs données.¦Classements IA¦Semaine¦{{count}} entrées classées¦{{count}} éditions publiées¦Mis à jour :¦Aussi disponible en¦Rang¦Nom¦Score¦Mouvement¦Source¦Profil¦Limites¦Preuves ({{count}})¦Méthode et limites¦NOUVEAU¦Dépôt¦Éditeur¦Test indépendant¦Benchmark¦Éditorial',
  bg: 'AI класации¦Датирани и подкрепени с източници AI класации, изградени по публикувани методи.¦Разгледайте датирани класации с техните кандидати, източници и публикувани методи.¦Отворете класацията →¦Все още няма готово локализирано издание. Прегледаните класации ще се появят след публикуване на данните им.¦AI класации¦Седмица¦{{count}} класирани записа¦{{count}} публикувани издания¦Обновено:¦Наличен и на¦Ранг¦Име¦Резултат¦Промяна¦Източник¦Профил¦Ограничения¦Доказателства ({{count}})¦Методика и ограничения¦НОВО¦Хранилище¦Издател¦Независим тест¦Бенчмарк¦Редакционен избор',
  hr: 'AI ljestvice¦Datirane AI ljestvice s izvorima i objavljenim metodama.¦Istražite datirane ljestvice, njihove kandidate, izvore i objavljene metode.¦Otvori ljestvicu →¦Lokalizirano izdanje još nije spremno. Pregledane ljestvice pojavit će se nakon objave njihovih podataka.¦AI ljestvice¦Tjedan¦{{count}} rangiranih stavki¦{{count}} objavljenih izdanja¦Ažurirano:¦Dostupno i na¦Rang¦Naziv¦Rezultat¦Pomak¦Izvor¦Profil¦Ograničenja¦Dokazi ({{count}})¦Metodologija i ograničenja¦NOVO¦Repozitorij¦Izdavač¦Neovisni test¦Benchmark¦Urednički odabir',
  cs: 'Žebříčky AI¦Datované žebříčky AI se zdroji a zveřejněnými metodami.¦Prozkoumejte datované žebříčky, jejich kandidáty, zdroje a zveřejněné metody.¦Otevřít žebříček →¦Lokalizované vydání zatím není připravené. Zkontrolované žebříčky se zobrazí po zveřejnění jejich dat.¦Žebříčky AI¦Týden¦{{count}} seřazených položek¦{{count}} zveřejněných vydání¦Aktualizováno:¦Dostupné také v¦Pořadí¦Název¦Skóre¦Posun¦Zdroj¦Profil¦Omezení¦Důkazy ({{count}})¦Metodika a omezení¦NOVÉ¦Repozitář¦Vydavatel¦Nezávislý test¦Benchmark¦Redakční výběr',
  da: 'AI-ranglister¦Daterede AI-ranglister med kilder og offentliggjorte metoder.¦Udforsk daterede ranglister med kandidater, kilder og offentliggjorte metoder.¦Åbn rangliste →¦En lokaliseret udgave er ikke klar endnu. Gennemgåede ranglister vises, når deres data er offentliggjort.¦AI-ranglister¦Uge¦{{count}} rangerede poster¦{{count}} offentliggjorte udgaver¦Opdateret:¦Også tilgængelig på¦Rang¦Navn¦Score¦Ændring¦Kilde¦Profil¦Begrænsninger¦Dokumentation ({{count}})¦Metode og begrænsninger¦NY¦Kodelager¦Udgiver¦Uafhængig test¦Benchmark¦Redaktionel vurdering',
  nl: 'AI-ranglijsten¦Gedateerde AI-ranglijsten met bronnen en gepubliceerde methoden.¦Bekijk gedateerde ranglijsten met kandidaten, bronnen en gepubliceerde methoden.¦Ranglijst openen →¦Er is nog geen gelokaliseerde editie klaar. Beoordeelde ranglijsten verschijnen zodra hun gegevens zijn gepubliceerd.¦AI-ranglijsten¦Week¦{{count}} gerangschikte items¦{{count}} gepubliceerde edities¦Bijgewerkt:¦Ook beschikbaar in¦Rang¦Naam¦Score¦Verandering¦Bron¦Profiel¦Beperkingen¦Bewijs ({{count}})¦Methode en beperkingen¦NIEUW¦Repository¦Uitgever¦Onafhankelijke test¦Benchmark¦Redactioneel',
  et: 'AI-edetabelid¦Kuupäevastatud ja allikatega AI-edetabelid, mis põhinevad avaldatud meetoditel.¦Tutvu kuupäevastatud edetabelitega ning nende kandidaatide, allikate ja avaldatud meetoditega.¦Ava edetabel →¦Lokaliseeritud väljaanne pole veel valmis. Ülevaadatud edetabelid ilmuvad pärast andmete avaldamist.¦AI-edetabelid¦Nädal¦{{count}} järjestatud kirjet¦{{count}} avaldatud väljaannet¦Uuendatud:¦Saadaval ka keeles¦Koht¦Nimi¦Skoor¦Muutus¦Allikas¦Profiil¦Piirangud¦Tõendid ({{count}})¦Meetod ja piirangud¦UUS¦Koodihoidla¦Väljaandja¦Sõltumatu test¦Võrdlustest¦Toimetuse valik',
  fi: 'Tekoälyrankkaukset¦Päivätyt ja lähteistetyt tekoälyrankkaukset, joiden menetelmät on julkaistu.¦Tutustu päivättyihin rankkauksiin, niiden ehdokkaisiin, lähteisiin ja julkaistuihin menetelmiin.¦Avaa ranking →¦Käännettyä julkaisua ei ole vielä valmiina. Tarkistetut rankkaukset näkyvät, kun niiden tiedot on julkaistu.¦Tekoälyrankkaukset¦Viikko¦{{count}} sijoitettua kohdetta¦{{count}} julkaistua painosta¦Päivitetty:¦Saatavilla myös kielellä¦Sija¦Nimi¦Pisteet¦Muutos¦Lähde¦Profiili¦Rajoitukset¦Näyttö ({{count}})¦Menetelmä ja rajoitukset¦UUSI¦Tietovarasto¦Julkaisija¦Riippumaton testi¦Vertailutesti¦Toimituksellinen arvio',
  de: 'KI-Ranglisten¦Datierte KI-Ranglisten mit Quellen und veröffentlichten Methoden.¦Entdecken Sie datierte Ranglisten mit Kandidaten, Quellen und veröffentlichten Methoden.¦Rangliste öffnen →¦Eine lokalisierte Ausgabe ist noch nicht verfügbar. Geprüfte Ranglisten erscheinen nach Veröffentlichung ihrer Daten.¦KI-Ranglisten¦Woche¦{{count}} gelistete Einträge¦{{count}} veröffentlichte Ausgaben¦Aktualisiert:¦Auch verfügbar auf¦Rang¦Name¦Punktzahl¦Veränderung¦Quelle¦Profil¦Einschränkungen¦Belege ({{count}})¦Methode und Einschränkungen¦NEU¦Repository¦Herausgeber¦Unabhängiger Test¦Benchmark¦Redaktionelle Auswahl',
  el: 'Κατατάξεις AI¦Χρονολογημένες κατατάξεις AI με πηγές και δημοσιευμένες μεθόδους.¦Εξερευνήστε χρονολογημένες κατατάξεις, υποψηφίους, πηγές και δημοσιευμένες μεθόδους.¦Άνοιγμα κατάταξης →¦Δεν υπάρχει ακόμη έτοιμη τοπική έκδοση. Οι ελεγμένες κατατάξεις θα εμφανιστούν όταν δημοσιευτούν τα δεδομένα τους.¦Κατατάξεις AI¦Εβδομάδα¦{{count}} καταχωρίσεις κατάταξης¦{{count}} δημοσιευμένες εκδόσεις¦Ενημερώθηκε:¦Διαθέσιμο και στα¦Θέση¦Όνομα¦Βαθμολογία¦Μεταβολή¦Πηγή¦Προφίλ¦Περιορισμοί¦Τεκμήρια ({{count}})¦Μεθοδολογία και περιορισμοί¦ΝΕΟ¦Αποθετήριο¦Εκδότης¦Ανεξάρτητη δοκιμή¦Benchmark¦Συντακτική επιλογή',
  hu: 'MI-ranglisták¦Dátummal és forrásokkal ellátott MI-ranglisták közzétett módszertan alapján.¦Fedezze fel a dátummal ellátott ranglistákat, jelöltjeiket, forrásaikat és közzétett módszereiket.¦Ranglista megnyitása →¦Még nincs kész lokalizált kiadás. Az ellenőrzött ranglisták az adatok közzététele után jelennek meg.¦MI-ranglisták¦Hét¦{{count}} rangsorolt elem¦{{count}} közzétett kiadás¦Frissítve:¦Elérhető ezen a nyelven is¦Helyezés¦Név¦Pontszám¦Változás¦Forrás¦Profil¦Korlátok¦Bizonyíték ({{count}})¦Módszertan és korlátok¦ÚJ¦Adattár¦Kiadó¦Független teszt¦Benchmark¦Szerkesztői válogatás',
  ga: 'Ranguithe IS¦Ranguithe IS dátaithe le foinsí agus modhanna foilsithe.¦Féach ar ranguithe dátaithe, a n-iarrthóirí, a bhfoinsí agus a modhanna foilsithe.¦Oscail an rangú →¦Níl eagrán logánaithe réidh fós. Beidh ranguithe athbhreithnithe le feiceáil nuair a fhoilseofar a gcuid sonraí.¦Ranguithe IS¦Seachtain¦{{count}} iontráil rangaithe¦{{count}} eagrán foilsithe¦Nuashonraithe:¦Ar fáil freisin i¦Rang¦Ainm¦Scór¦Athrú¦Foinse¦Próifíl¦Teorainneacha¦Fianaise ({{count}})¦Modheolaíocht agus teorainneacha¦NUA¦Stór cód¦Foilsitheoir¦Tástáil neamhspleách¦Tagarmharc¦Rogha eagarthóireachta',
  it: 'Classifiche IA¦Classifiche IA datate, con fonti e metodi pubblicati.¦Esplora classifiche datate, candidati, fonti e metodi pubblicati.¦Apri la classifica →¦Non è ancora pronta un’edizione localizzata. Le classifiche revisionate appariranno dopo la pubblicazione dei dati.¦Classifiche IA¦Settimana¦{{count}} voci in classifica¦{{count}} edizioni pubblicate¦Aggiornato:¦Disponibile anche in¦Posizione¦Nome¦Punteggio¦Variazione¦Fonte¦Profilo¦Limiti¦Prove ({{count}})¦Metodo e limiti¦NUOVO¦Repository¦Editore¦Test indipendente¦Benchmark¦Selezione editoriale',
  lv: 'MI reitingi¦Datēti MI reitingi ar avotiem un publicētām metodēm.¦Iepazīstiet datētus reitingus, to kandidātus, avotus un publicētās metodes.¦Atvērt reitingu →¦Lokalizēts izdevums vēl nav gatavs. Pārskatītie reitingi būs pieejami pēc datu publicēšanas.¦MI reitingi¦Nedēļa¦{{count}} sarindoti ieraksti¦{{count}} publicēti izdevumi¦Atjaunināts:¦Pieejams arī valodā¦Vieta¦Nosaukums¦Rezultāts¦Izmaiņas¦Avots¦Profils¦Ierobežojumi¦Pierādījumi ({{count}})¦Metodika un ierobežojumi¦JAUNS¦Koda krātuve¦Izdevējs¦Neatkarīgs tests¦Etalonmērījums¦Redakcijas izvēle',
  lt: 'DI reitingai¦Datomis ir šaltiniais pagrįsti DI reitingai pagal paskelbtus metodus.¦Peržiūrėkite datuotus reitingus, kandidatus, šaltinius ir paskelbtus metodus.¦Atverti reitingą →¦Lokalizuotas leidimas dar neparengtas. Peržiūrėti reitingai bus rodomi paskelbus jų duomenis.¦DI reitingai¦Savaitė¦{{count}} surikiuotų įrašų¦{{count}} paskelbtų leidimų¦Atnaujinta:¦Taip pat pasiekiama kalba¦Vieta¦Pavadinimas¦Įvertis¦Pokytis¦Šaltinis¦Profilis¦Apribojimai¦Įrodymai ({{count}})¦Metodika ir apribojimai¦NAUJA¦Saugykla¦Leidėjas¦Nepriklausomas bandymas¦Etaloninis testas¦Redakcijos atranka',
  mt: 'Klassifiki tal-IA¦Klassifiki tal-IA bid-dati, sorsi u metodi ppubblikati.¦Esplora klassifiki bid-dati, il-kandidati, is-sorsi u l-metodi ppubblikati tagħhom.¦Iftaħ il-klassifika →¦Għadha mhix lesta edizzjoni lokalizzata. Il-klassifiki riveduti jidhru wara l-pubblikazzjoni tad-dejta tagħhom.¦Klassifiki tal-IA¦Ġimgħa¦{{count}} entrata kklassifikata¦{{count}} edizzjoni ppubblikata¦Aġġornat:¦Disponibbli wkoll fi¦Rank¦Isem¦Punteġġ¦Bidla¦Sors¦Profil¦Limitazzjonijiet¦Evidenza ({{count}})¦Metodoloġija u limitazzjonijiet¦ĠDIDA¦Repożitorju¦Pubblikatur¦Test indipendenti¦Benchmark¦Għażla editorjali',
  pl: 'Rankingi AI¦Datowane rankingi AI ze źródłami i opublikowaną metodologią.¦Poznaj datowane rankingi, kandydatów, źródła i opublikowane metody.¦Otwórz ranking →¦Zlokalizowana edycja nie jest jeszcze gotowa. Sprawdzone rankingi pojawią się po opublikowaniu danych.¦Rankingi AI¦Tydzień¦{{count}} sklasyfikowanych pozycji¦{{count}} opublikowanych edycji¦Aktualizacja:¦Dostępne także w¦Miejsce¦Nazwa¦Wynik¦Zmiana¦Źródło¦Profil¦Ograniczenia¦Dowody ({{count}})¦Metodologia i ograniczenia¦NOWE¦Repozytorium¦Wydawca¦Niezależny test¦Benchmark¦Wybór redakcji',
  pt: 'Rankings de IA¦Rankings de IA datados, com fontes e métodos publicados.¦Explore rankings datados, candidatos, fontes e métodos publicados.¦Abrir ranking →¦Ainda não há uma edição localizada pronta. Os rankings revistos aparecem depois da publicação dos dados.¦Rankings de IA¦Semana¦{{count}} entradas classificadas¦{{count}} edições publicadas¦Atualizado:¦Também disponível em¦Posição¦Nome¦Pontuação¦Variação¦Fonte¦Perfil¦Limitações¦Evidências ({{count}})¦Metodologia e limitações¦NOVO¦Repositório¦Editor¦Teste independente¦Benchmark¦Seleção editorial',
  ro: 'Clasamente IA¦Clasamente IA datate, cu surse și metode publicate.¦Explorați clasamente datate, candidații, sursele și metodele publicate.¦Deschide clasamentul →¦Nu există încă o ediție localizată pregătită. Clasamentele revizuite vor apărea după publicarea datelor.¦Clasamente IA¦Săptămâna¦{{count}} intrări clasate¦{{count}} ediții publicate¦Actualizat:¦Disponibil și în¦Poziție¦Nume¦Scor¦Modificare¦Sursă¦Profil¦Limitări¦Dovezi ({{count}})¦Metodologie și limitări¦NOU¦Depozit de cod¦Editor¦Test independent¦Benchmark¦Selecție editorială',
  sk: 'Rebríčky AI¦Datované rebríčky AI so zdrojmi a zverejnenými metódami.¦Preskúmajte datované rebríčky, ich kandidátov, zdroje a zverejnené metódy.¦Otvoriť rebríček →¦Lokalizované vydanie zatiaľ nie je pripravené. Skontrolované rebríčky sa zobrazia po zverejnení ich údajov.¦Rebríčky AI¦Týždeň¦{{count}} zoradených položiek¦{{count}} zverejnených vydaní¦Aktualizované:¦Dostupné aj v¦Poradie¦Názov¦Skóre¦Zmena¦Zdroj¦Profil¦Obmedzenia¦Dôkazy ({{count}})¦Metodika a obmedzenia¦NOVÉ¦Repozitár¦Vydavateľ¦Nezávislý test¦Benchmark¦Redakčný výber',
  sl: 'Lestvice UI¦Datirane lestvice UI z viri in objavljenimi metodami.¦Oglejte si datirane lestvice, kandidate, vire in objavljene metode.¦Odpri lestvico →¦Lokalizirana izdaja še ni pripravljena. Pregledane lestvice bodo prikazane po objavi podatkov.¦Lestvice UI¦Teden¦{{count}} razvrščenih vnosov¦{{count}} objavljenih izdaj¦Posodobljeno:¦Na voljo tudi v¦Mesto¦Ime¦Rezultat¦Sprememba¦Vir¦Profil¦Omejitve¦Dokazi ({{count}})¦Metodologija in omejitve¦NOVO¦Repozitorij¦Založnik¦Neodvisni test¦Primerjalni test¦Uredniški izbor',
  es: 'Rankings de IA¦Rankings de IA fechados, con fuentes y métodos publicados.¦Explora rankings fechados con sus candidatos, fuentes y métodos publicados.¦Abrir ranking →¦Aún no hay una edición localizada lista. Los rankings revisados aparecerán cuando se publiquen sus datos.¦Rankings de IA¦Semana¦{{count}} elementos clasificados¦{{count}} ediciones publicadas¦Actualizado:¦También disponible en¦Puesto¦Nombre¦Puntuación¦Cambio¦Fuente¦Perfil¦Limitaciones¦Pruebas ({{count}})¦Metodología y limitaciones¦NUEVO¦Repositorio¦Editor¦Prueba independiente¦Benchmark¦Selección editorial',
  sv: 'AI-rankningar¦Daterade AI-rankningar med källor och publicerade metoder.¦Utforska daterade rankningar med kandidater, källor och publicerade metoder.¦Öppna rankning →¦En lokaliserad utgåva är inte klar ännu. Granskade rankningar visas när deras data har publicerats.¦AI-rankningar¦Vecka¦{{count}} rankade poster¦{{count}} publicerade utgåvor¦Uppdaterad:¦Även tillgänglig på¦Placering¦Namn¦Poäng¦Förändring¦Källa¦Profil¦Begränsningar¦Underlag ({{count}})¦Metod och begränsningar¦NY¦Kodarkiv¦Utgivare¦Oberoende test¦Benchmark¦Redaktionellt urval',
  sq: 'Renditje të IA-së¦Renditje të IA-së me data, burime dhe metoda të publikuara.¦Eksploroni renditje me data, kandidatë, burime dhe metoda të publikuara.¦Hap renditjen →¦Ende nuk ka një botim të lokalizuar gati. Renditjet e shqyrtuara do të shfaqen pas publikimit të të dhënave.¦Renditje të IA-së¦Java¦{{count}} hyrje të renditura¦{{count}} botime të publikuara¦Përditësuar:¦E disponueshme edhe në¦Renditja¦Emri¦Rezultati¦Ndryshimi¦Burimi¦Profili¦Kufizimet¦Dëshmi ({{count}})¦Metodologjia dhe kufizimet¦E RE¦Depo kodi¦Botuesi¦Test i pavarur¦Benchmark¦Përzgjedhje editoriale',
  be: 'Рэйтынгі ШІ¦Датаваныя рэйтынгі ШІ з крыніцамі і апублікаванымі метадамі.¦Праглядайце датаваныя рэйтынгі, кандыдатаў, крыніцы і апублікаваныя метады.¦Адкрыць рэйтынг →¦Лакалізаванае выданне яшчэ не гатова. Правераныя рэйтынгі з’явяцца пасля публікацыі даных.¦Рэйтынгі ШІ¦Тыдзень¦{{count}} ранжыраваных запісаў¦{{count}} апублікаваных выданняў¦Абноўлена:¦Таксама даступна на¦Месца¦Назва¦Ацэнка¦Змена¦Крыніца¦Профіль¦Абмежаванні¦Доказы ({{count}})¦Метадалогія і абмежаванні¦НОВАЕ¦Рэпазіторый¦Выдавец¦Незалежны тэст¦Бенчмарк¦Рэдакцыйны выбар',
  bs: 'AI rang-liste¦Datirane AI rang-liste s izvorima i objavljenim metodama.¦Istražite datirane rang-liste, kandidate, izvore i objavljene metode.¦Otvori rang-listu →¦Lokalizovano izdanje još nije spremno. Pregledane rang-liste bit će prikazane nakon objave podataka.¦AI rang-liste¦Sedmica¦{{count}} rangiranih stavki¦{{count}} objavljenih izdanja¦Ažurirano:¦Dostupno i na¦Rang¦Naziv¦Rezultat¦Promjena¦Izvor¦Profil¦Ograničenja¦Dokazi ({{count}})¦Metodologija i ograničenja¦NOVO¦Repozitorij¦Izdavač¦Nezavisni test¦Benchmark¦Urednički izbor',
  is: 'Gervigreindarlistar¦Dagsettir listar um gervigreind með heimildum og birtum aðferðum.¦Skoðaðu dagsetta lista, þátttakendur, heimildir og birtar aðferðir.¦Opna lista →¦Staðfærð útgáfa er ekki tilbúin enn. Yfirfarnir listar birtast þegar gögnin hafa verið birt.¦Gervigreindarlistar¦Vika¦{{count}} raðaðar færslur¦{{count}} birtar útgáfur¦Uppfært:¦Einnig í boði á¦Sæti¦Nafn¦Stig¦Breyting¦Heimild¦Prófíll¦Takmarkanir¦Gögn ({{count}})¦Aðferð og takmarkanir¦NÝTT¦Kóðageymsla¦Útgefandi¦Óháð prófun¦Viðmiðunarpróf¦Ritstjórnarval',
  mk: 'Рангирања за ВИ¦Датирани рангирања за ВИ со извори и објавени методи.¦Истражете датирани рангирања, кандидати, извори и објавени методи.¦Отвори рангирање →¦Локализирано издание сè уште не е подготвено. Прегледаните рангирања ќе се појават по објавувањето на податоците.¦Рангирања за ВИ¦Недела¦{{count}} рангирани ставки¦{{count}} објавени изданија¦Ажурирано:¦Достапно и на¦Ранг¦Име¦Резултат¦Промена¦Извор¦Профил¦Ограничувања¦Докази ({{count}})¦Методологија и ограничувања¦НОВО¦Складиште на код¦Издавач¦Независен тест¦Бенчмарк¦Уреднички избор',
  nb: 'KI-rangeringer¦Dato- og kildebaserte KI-rangeringer med publiserte metoder.¦Utforsk daterte rangeringer med kandidater, kilder og publiserte metoder.¦Åpne rangering →¦En lokalisert utgave er ikke klar ennå. Gjennomgåtte rangeringer vises når dataene er publisert.¦KI-rangeringer¦Uke¦{{count}} rangerte oppføringer¦{{count}} publiserte utgaver¦Oppdatert:¦Også tilgjengelig på¦Rang¦Navn¦Poengsum¦Endring¦Kilde¦Profil¦Begrensninger¦Dokumentasjon ({{count}})¦Metode og begrensninger¦NY¦Kodelager¦Utgiver¦Uavhengig test¦Referansetest¦Redaksjonelt utvalg',
  nn: 'KI-rangeringar¦Dato- og kjeldebaserte KI-rangeringar med publiserte metodar.¦Utforsk daterte rangeringar med kandidatar, kjelder og publiserte metodar.¦Opne rangering →¦Ei lokalisert utgåve er ikkje klar enno. Gjennomgåtte rangeringar kjem når dataa er publiserte.¦KI-rangeringar¦Veke¦{{count}} rangerte oppføringar¦{{count}} publiserte utgåver¦Oppdatert:¦Òg tilgjengeleg på¦Rang¦Namn¦Poengsum¦Endring¦Kjelde¦Profil¦Avgrensingar¦Dokumentasjon ({{count}})¦Metode og avgrensingar¦NY¦Kodelager¦Utgjevar¦Uavhengig test¦Referansetest¦Redaksjonelt utval',
  ru: 'Рейтинги ИИ¦Датированные рейтинги ИИ с источниками и опубликованными методиками.¦Изучите датированные рейтинги, кандидатов, источники и опубликованные методики.¦Открыть рейтинг →¦Локализованный выпуск ещё не готов. Проверенные рейтинги появятся после публикации данных.¦Рейтинги ИИ¦Неделя¦{{count}} позиций в рейтинге¦{{count}} опубликованных выпусков¦Обновлено:¦Также доступно на¦Место¦Название¦Оценка¦Изменение¦Источник¦Профиль¦Ограничения¦Подтверждения ({{count}})¦Методика и ограничения¦НОВОЕ¦Репозиторий¦Издатель¦Независимый тест¦Бенчмарк¦Редакционный выбор',
  'sr-cyrl':
    'AI рангирања¦Датирана AI рангирања са изворима и објављеним методама.¦Истражите датирана рангирања, кандидате, изворе и објављене методе.¦Отвори рангирање →¦Локализовано издање још није спремно. Прегледана рангирања ће се појавити након објаве података.¦AI рангирања¦Недеља¦{{count}} рангираних ставки¦{{count}} објављених издања¦Ажурирано:¦Доступно и на¦Ранг¦Назив¦Резултат¦Промена¦Извор¦Профил¦Ограничења¦Докази ({{count}})¦Методологија и ограничења¦НОВО¦Репозиторијум¦Издавач¦Независни тест¦Бенчмарк¦Уреднички избор',
  'sr-latn':
    'AI rangiranja¦Datirana AI rangiranja sa izvorima i objavljenim metodama.¦Istražite datirana rangiranja, kandidate, izvore i objavljene metode.¦Otvori rangiranje →¦Lokalizovano izdanje još nije spremno. Pregledana rangiranja pojaviće se nakon objave podataka.¦AI rangiranja¦Nedelja¦{{count}} rangiranih stavki¦{{count}} objavljenih izdanja¦Ažurirano:¦Dostupno i na¦Rang¦Naziv¦Rezultat¦Promena¦Izvor¦Profil¦Ograničenja¦Dokazi ({{count}})¦Metodologija i ograničenja¦NOVO¦Repozitorijum¦Izdavač¦Nezavisni test¦Benchmark¦Urednički izbor',
  uk: 'Рейтинги ШІ¦Датовані рейтинги ШІ з джерелами та опублікованими методами.¦Перегляньте датовані рейтинги, кандидатів, джерела та опубліковані методи.¦Відкрити рейтинг →¦Локалізований випуск ще не готовий. Перевірені рейтинги з’являться після публікації даних.¦Рейтинги ШІ¦Тиждень¦{{count}} позицій у рейтингу¦{{count}} опублікованих випусків¦Оновлено:¦Також доступно мовою¦Місце¦Назва¦Оцінка¦Зміна¦Джерело¦Профіль¦Обмеження¦Підтвердження ({{count}})¦Методика та обмеження¦НОВЕ¦Репозиторій¦Видавець¦Незалежний тест¦Бенчмарк¦Редакційний вибір',
  tr: 'Yapay zekâ sıralamaları¦Yayınlanmış yöntemlere dayanan, tarihli ve kaynaklı yapay zekâ sıralamaları.¦Adayları, kaynakları ve yayımlanmış yöntemleriyle tarihli sıralamaları keşfedin.¦Sıralamayı aç →¦Yerelleştirilmiş bir liste henüz hazır değil. İncelenen sıralamalar, verileri yayımlandıktan sonra görünür.¦Yapay zekâ sıralamaları¦Hafta¦{{count}} sıralanmış kayıt¦{{count}} yayımlanmış liste¦Güncellendi:¦Şu dilde de mevcut¦Sıra¦Ad¦Puan¦Değişim¦Kaynak¦Profil¦Sınırlamalar¦Kanıt ({{count}})¦Yöntem ve sınırlamalar¦YENİ¦Depo¦Yayıncı¦Bağımsız test¦Karşılaştırma testi¦Editör seçimi',
  hy: 'ԱԲ վարկանիշներ¦Ամսաթվերով և աղբյուրներով ԱԲ վարկանիշներ՝ հրապարակված մեթոդաբանությամբ։¦Ուսումնասիրեք ամսաթվերով վարկանիշները, թեկնածուները, աղբյուրներն ու հրապարակված մեթոդները։¦Բացել վարկանիշը →¦Տեղայնացված թողարկումը դեռ պատրաստ չէ։ Վերանայված վարկանիշները կհայտնվեն տվյալների հրապարակումից հետո։¦ԱԲ վարկանիշներ¦Շաբաթ¦{{count}} դասակարգված գրառում¦{{count}} հրապարակված թողարկում¦Թարմացվել է՝¦Հասանելի է նաև¦Տեղ¦Անուն¦Միավոր¦Փոփոխություն¦Աղբյուր¦Պրոֆիլ¦Սահմանափակումներ¦Ապացույցներ ({{count}})¦Մեթոդաբանություն և սահմանափակումներ¦ՆՈՐ¦Կոդի պահոց¦Հրատարակիչ¦Անկախ փորձարկում¦Համեմատական թեստ¦Խմբագրական ընտրություն',
  az: 'Süni intellekt reytinqləri¦Dərc olunmuş metodlara əsaslanan tarixli və mənbəli süni intellekt reytinqləri.¦Namizədləri, mənbələri və dərc olunmuş metodları ilə tarixli reytinqləri araşdırın.¦Reytinqi aç →¦Lokallaşdırılmış buraxılış hələ hazır deyil. Yoxlanmış reytinqlər məlumatlar dərc edildikdən sonra görünəcək.¦Süni intellekt reytinqləri¦Həftə¦{{count}} sıralanmış qeyd¦{{count}} dərc edilmiş buraxılış¦Yenilənib:¦Bu dildə də mövcuddur¦Yer¦Ad¦Bal¦Dəyişiklik¦Mənbə¦Profil¦Məhdudiyyətlər¦Sübutlar ({{count}})¦Metodologiya və məhdudiyyətlər¦YENİ¦Kod deposu¦Nəşriyyatçı¦Müstəqil test¦Müqayisə testi¦Redaksiya seçimi',
  ka: 'ხელოვნური ინტელექტის რეიტინგები¦თარიღიანი AI რეიტინგები წყაროებითა და გამოქვეყნებული მეთოდებით.¦იხილეთ თარიღიანი რეიტინგები, კანდიდატები, წყაროები და გამოქვეყნებული მეთოდები.¦რეიტინგის გახსნა →¦ლოკალიზებული გამოცემა ჯერ მზად არ არის. შემოწმებული რეიტინგები მონაცემების გამოქვეყნების შემდეგ გამოჩნდება.¦AI რეიტინგები¦კვირა¦{{count}} დალაგებული ჩანაწერი¦{{count}} გამოქვეყნებული გამოცემა¦განახლებულია:¦ასევე ხელმისაწვდომია¦ადგილი¦სახელი¦ქულა¦ცვლილება¦წყარო¦პროფილი¦შეზღუდვები¦მტკიცებულება ({{count}})¦მეთოდოლოგია და შეზღუდვები¦ახალი¦საცავი¦გამომცემელი¦დამოუკიდებელი ტესტი¦შედარებითი ტესტი¦რედაქციული არჩევანი',
  lb: 'KI-Ranglëschten¦Datéiert KI-Ranglëschte mat Quellen a publizéierte Methoden.¦Entdeckt datéiert Ranglëschte mat Kandidaten, Quellen a publizéierte Methoden.¦Ranglëscht opmaachen →¦Eng lokaliséiert Editioun ass nach net prett. Iwwerpréifte Ranglëschte kommen no der Verëffentlechung vun hiren Donnéeën.¦KI-Ranglëschten¦Woch¦{{count}} klasséiert Entréen¦{{count}} publizéiert Editiounen¦Aktualiséiert:¦Och disponibel op¦Plaz¦Numm¦Score¦Ännerung¦Quell¦Profil¦Aschränkungen¦Beweiser ({{count}})¦Methodologie an Aschränkungen¦NEI¦Repository¦Editeur¦Onofhängegen Test¦Benchmark¦Redaktionell Auswiel',
  ca: 'Rànquings d’IA¦Rànquings d’IA datats, amb fonts i mètodes publicats.¦Explora rànquings datats amb candidats, fonts i mètodes publicats.¦Obre el rànquing →¦Encara no hi ha cap edició localitzada a punt. Els rànquings revisats apareixeran quan se’n publiquin les dades.¦Rànquings d’IA¦Setmana¦{{count}} elements classificats¦{{count}} edicions publicades¦Actualitzat:¦També disponible en¦Posició¦Nom¦Puntuació¦Canvi¦Font¦Perfil¦Limitacions¦Proves ({{count}})¦Metodologia i limitacions¦NOU¦Repositori¦Editor¦Prova independent¦Benchmark¦Selecció editorial',
  eu: 'AI sailkapenak¦Data eta iturriak dituzten AI sailkapenak, argitaratutako metodoen arabera.¦Arakatu data, hautagai, iturri eta metodo argitaratuak dituzten sailkapenak.¦Ireki sailkapena →¦Oraindik ez dago itzulitako ediziorik prest. Berrikusitako sailkapenak datuak argitaratzean agertuko dira.¦AI sailkapenak¦Astea¦{{count}} sarrera sailkatu¦{{count}} edizio argitaratu¦Eguneratua:¦Hizkuntza honetan ere bai¦Sailkapena¦Izena¦Puntuazioa¦Aldaketa¦Iturria¦Profila¦Mugak¦Frogak ({{count}})¦Metodologia eta mugak¦BERRIA¦Kode-biltegia¦Argitaratzailea¦Proba independentea¦Erreferentzia-proba¦Editoreen hautaketa',
  gl: 'Clasificacións de IA¦Clasificacións de IA datadas, con fontes e métodos publicados.¦Explora clasificacións datadas coas súas candidaturas, fontes e métodos publicados.¦Abrir clasificación →¦Aínda non hai unha edición localizada lista. As clasificacións revisadas aparecerán ao publicar os datos.¦Clasificacións de IA¦Semana¦{{count}} entradas clasificadas¦{{count}} edicións publicadas¦Actualizado:¦Tamén dispoñible en¦Posto¦Nome¦Puntuación¦Cambio¦Fonte¦Perfil¦Limitacións¦Probas ({{count}})¦Metodoloxía e limitacións¦NOVO¦Repositorio¦Editor¦Proba independente¦Benchmark¦Selección editorial',
  cy: 'Safleoedd AI¦Safleoedd AI â dyddiadau a ffynonellau, yn seiliedig ar ddulliau cyhoeddedig.¦Archwiliwch safleoedd dyddiedig, eu hymgeiswyr, eu ffynonellau a’u dulliau cyhoeddedig.¦Agor y safle →¦Nid oes rhifyn lleol yn barod eto. Bydd safleoedd a adolygwyd yn ymddangos ar ôl cyhoeddi’r data.¦Safleoedd AI¦Wythnos¦{{count}} cofnod wedi’u rhestru¦{{count}} rhifyn wedi’u cyhoeddi¦Diweddarwyd:¦Ar gael hefyd yn¦Safle¦Enw¦Sgôr¦Newid¦Ffynhonnell¦Proffil¦Cyfyngiadau¦Tystiolaeth ({{count}})¦Methodoleg a chyfyngiadau¦NEWYDD¦Ystorfa¦Cyhoeddwr¦Prawf annibynnol¦Meincnod¦Dewis golygyddol',
  gd: 'Rangachaidhean AI¦Rangachaidhean AI le cinn-latha, tobraichean agus modhan foillsichte.¦Rannsaich rangachaidhean le cinn-latha, tagraichean, tobraichean agus modhan foillsichte.¦Fosgail an rangachadh →¦Chan eil deasachadh ionadaichte deiseil fhathast. Nochdaidh na rangachaidhean ath-sgrùdaichte nuair a thèid an dàta fhoillseachadh.¦Rangachaidhean AI¦Seachdain¦{{count}} inntrigeadh san rangachadh¦{{count}} deasachaidhean foillsichte¦Air ùrachadh:¦Ri fhaighinn ann an¦Rang¦Ainm¦Sgòr¦Atharrachadh¦Tobar¦Pròifil¦Cuingeachaidhean¦Fianais ({{count}})¦Dòigh-obrach agus cuingeachaidhean¦ÙR¦Stòr-tasgaidh¦Foillsichear¦Deuchainn neo-eisimeileach¦Deuchainn coimeasach¦Roghainn deasachaidh',
  fo: 'AI-listar¦Dagfestir AI-listar við keldum og almannakunngjørdum háttum.¦Kanna dagfestar listar við valevnum, keldum og almannakunngjørdum háttum.¦Opna listan →¦Ein staðsett útgáva er ikki klár enn. Yvirfarnir listar verða vístir, tá ið dátan er almannakunngjørd.¦AI-listar¦Vika¦{{count}} raðfestar færslur¦{{count}} almannakunngjørdar útgávur¦Dagført:¦Eisini tøkt á¦Pláss¦Navn¦Stig¦Broyting¦Kelda¦Profil¦Avmarkingar¦Prógv ({{count}})¦Háttur og avmarkingar¦NÝTT¦Keldugoymsla¦Útgevari¦Óheft roynd¦Samanberingarroynd¦Ritstjórnarval',
  rm: 'Classificaziuns d’IA¦Classificaziuns d’IA datadas cun funtaunas e metodas publitgadas.¦Scuvri classificaziuns datadas, lur candidats, funtaunas e metodas publitgadas.¦Avrir la classificaziun →¦Anc n’è nagina ediziun translatada pronta. Las classificaziuns controlladas cumparan suenter la publicaziun da las datas.¦Classificaziuns d’IA¦Emna¦{{count}} entradas ordinadas¦{{count}} ediziuns publitgadas¦Actualisà:¦Disponibel er en¦Plazza¦Num¦Puncts¦Midada¦Funtauna¦Profil¦Limitaziuns¦Cumprovas ({{count}})¦Metoda e limitaziuns¦NOV¦Archiv da code¦Editur¦Test independent¦Benchmark¦Selecziun editoriala',
  se: 'AI-rátnegat¦Dáhtáduvvon ja gálduid čájeheaddji AI-rátnegat almmuhuvvon vuogi mielde.¦Geahča dáhtáduvvon rátnegiid, kandidáhtaid, gálduid ja almmuhuvvon vuogi.¦Raba rátnegiid →¦Jorgaluvvon almmuhus ii leat vel geargan. Dárkkistuvvon rátnegat oidnojit go dieđut almmuhuvvojit.¦AI-rátnegat¦Vahkku¦{{count}} rátnejuvvon merkoša¦{{count}} almmuhuvvon almmuhusa¦Ođasmahttojuvvon:¦Gávdno maiddái giellain¦Sajádat¦Namma¦Poaŋŋu¦Rievdadus¦Gáldu¦Profiila¦Ráddjehusat¦Duođaštusat ({{count}})¦Vuohki ja ráddjehusat¦OĐAS¦Vuorká¦Almmuheaddji¦Iešheanalaš geahččaleapmi¦Benchmark¦Redakšuvnna válljen',
  sma: 'AI-rangeringh¦Biejjiehke AI-rangeringh gïjhkine jïh publiseradme vuekine.¦Loeh biejjiehke rangeringh, kandidath, gïjhkine jïh publiseradme vuekine.¦Rangeringem buektedh →¦Jarkoestamme biejjiehke teekste ij leah naemhtie. Tjaaleldh rangeringh vuejnieh gosse daate publiserad.¦AI-rangeringh¦Våhkoe¦{{count}} rangeringesijjieh¦{{count}} publiseradme teeksth¦Ođđistamme:¦Aaj gïelesne gååvnesieh¦Sijjie¦Nomme¦Poengh¦Jarkelimmie¦Gïjhkine¦Profiile¦Råajvarimmieh¦Duohtahtimmieh ({{count}})¦Vuöpie jïh råajvarimmieh¦OHTE¦Vuorke¦Publiseerije¦Iešheanalaš testeme¦Benchmark¦Redaksjovnen veeljeme',
  smj: 'AI-rátnegis¦Biejvvit ja gáldojt oajvvadit AI-rátnegis almmuhuvvam vuogij milta.¦Oajvvadit biejvvit rátnegijt, kandidáhtajt, gáldojt ja almmuhuvvam vuogijt.¦Rahpat rátnegis →¦Jorggalum almmuhus ij la gárves. Dárkkidum rátnegis vuoseduvvi gå diehto almmuhuvvi.¦AI-rátnegis¦Vahkko¦{{count}} rátnejuvvam merko¦{{count}} almmuhuvvam almmuhusá¦Ođasmahtedum:¦Aj gielan gávnnu¦Sajádahka¦Namma¦Punktah¦Rievddadus¦Gálldo¦Profijlla¦Ráddjem¦Duođaštusá ({{count}})¦Vuohke ja ráddjem¦OĐĐAS¦Vuorkkå¦Almmuheaddje¦Iešheanalaš tjuolbmastit¦Benchmark¦Redaksjåvnnå válljim',
  smn: 'AI-räähtiih¦Peividejum já lähdejuvvom AI-räähtiih almmustum tááhádâh mield.¦Uáini peividejum räähtiid, kandideetijd, lähdeid já almmustum tááhádâhid.¦Räähti avâ →¦Jorgâlum almmustume ij lah valmâš. Tárkkuum räähtiih čyettih teivâ almmustum maŋa.¦AI-räähtiih¦Vástuppeivi¦{{count}} räähtum kirjástusah¦{{count}} almmustum almmustumeh¦Ođâstittum:¦Lââi tun kievdid¦Sajattâh¦Nommâ¦Punktâh¦Molšâ¦Lähte¦Profiil¦Rájuhâh¦Tođâstusah ({{count}})¦Tááhádâh já rájuhâh¦UUSÂ¦Vuorkkâ¦Almmustehtee¦Iešheanalaš tástâ¦Benchmark¦Toimettee válljâm',
  sms: 'AI-rätǩǩõõzz¦Peiʹvvõõzz da lähteʹst AI-rätǩǩõõzz õõlǥtummuž vuõiggâd vueʹjjin.¦Ǩiõttǩe peiʹvvõõzz rätǩǩõõzzid, kandidaattid, lähteʹst da õõlǥtummuž vueʹjjin.¦Raajj rätǩǩõõzz →¦Jorgaalum õõlǥtummuš ij leäkku valmš. Tärkkstum rätǩǩõõzz čuäʹjet õõlǥtummuž maŋŋa.¦AI-rätǩǩõõzz¦Vååʹǩǩ¦{{count}} rätǩǩõõzz kirje¦{{count}} õõlǥtummuž eʹǩǩǩõõzz¦Ođđâʹt:¦Lââʹzzõsǩõs¦Sâjj¦Nõmm¦Pooŋǥ¦Muttâz¦Lähte¦Profiil¦Rájõõzz¦Tääzzõõzz ({{count}})¦Vueʹjj da rájõõzz¦OUDD¦Vuuʹǩǩ¦Õõlǥtõõzz¦Õhttõõzztest¦Benchmark¦Redaktiooʹr válljõs',
  yi: 'AI ראַנגירונגען¦דאַטירטע AI ראַנגירונגען מיט קוואַלן און פֿאַרעפֿנטלעכטע מעטאָדן.¦קוקט אויף דאַטירטע ראַנגירונגען, קאַנדידאַטן, קוואַלן און פֿאַרעפֿנטלעכטע מעטאָדן.¦עפֿענען די ראַנגירונג →¦קיין איבערגעזעצטע אויסגאַבע איז נאָך נישט גרייט. איבערגעקוקטע ראַנגירונגען וועלן דערשײַנען ווען די דאַטן ווערן פֿאַרעפֿנטלעכט.¦AI ראַנגירונגען¦וואָך¦{{count}} ראַנגירטע איינטראָגן¦{{count}} פֿאַרעפֿנטלעכטע אויסגאַבעס¦דערהײַנטיקט:¦אויך בנימצא אויף¦ראַנג¦נאָמען¦פּונקטן¦ענדערונג¦מקור¦פּראָפֿיל¦באַגרענעצונגען¦באַווײַזן ({{count}})¦מעטאָד און באַגרענעצונגען¦נײַ¦קאָד־ריפּאַזאַטאָרי¦אַרויסגעבער¦אומאָפּהענגיקער טעסט¦בענטשמאַרק¦רעדאַקציע־אויסקלײַב',
  rom: 'AI rankinga¦Rankinga AI datade, k-o źurya thaj metode publikime.¦Dikhe rankinga datade, kandidatura, źurya thaj metode publikime.¦Phir e rankingate →¦Nane akana lokalizime edicia. O kontrolime rankinga sikaven pes kana publikisarel pes o dato.¦AI rankinga¦Kurko¦{{count}} rangime zapisura¦{{count}} publikime edicije¦Aktualizime:¦Vi kadi čhibeste¦Than¦Anav¦Rezultato¦Paruvipe¦Źuro¦Profilo¦Limitacije¦Dokazi ({{count}})¦Metodologija thaj limitacije¦NEVO¦Repozitorija¦Publikatoro¦Nezavisno testo¦Benchmark¦Redakcijako izboro',
  br: 'Renabladoù IA¦Renabladoù IA gant deiziadoù, mammennioù ha metodologiezhioù embannet.¦Kit da welet renabladoù deiziadet, o c’hinnigidi, o mammennioù hag o metodologiezhioù.¦Digeriñ ar renabl →¦N’eus embannadur lec’hel prest ebet c’hoazh. Renabladoù adwelet a vo diskouezet pa vo embannet an roadennoù.¦Renabladoù IA¦Sizhun¦{{count}} elfenn renablet¦{{count}} embannadur embannet¦Hizivaet:¦Hegerz ivez e¦Renk¦Anv¦Merk¦Kemmoù¦Mammenn¦Profil¦Bevennoù¦Testennoù ({{count}})¦Metodologiezh ha bevennoù¦NEVEZ¦Mirlec’h kod¦Embanner¦Amprouenn dizalc’h¦Benchmark¦Dibab ar pennad-stur',
  co: 'Classifichi IA¦Classifichi IA datati cù fonti è metudi publicati.¦Scuprite classifichi datati, candidati, fonti è metudi publicati.¦Apri a classifica →¦Ùn’edizione lucalizata ùn hè ancu pronta. E classifichi riviste appareranu dopu a publicazione di i dati.¦Classifichi IA¦Simana¦{{count}} elementi classificati¦{{count}} edizioni publicati¦Aghjurnatu:¦Dispunibule dinù in¦Postu¦Nome¦Puntu¦Cambiamentu¦Fonte¦Profilu¦Limitazioni¦Pruve ({{count}})¦Metudu è limitazioni¦NOVU¦Repositoriu¦Editore¦Test indipendente¦Benchmark¦Scelta editoriale',
  oc: 'Classaments d’IA¦Classaments d’IA datats amb de fonts e de metòdes publicats.¦Explora de classaments datats, lors candidats, lors fonts e lors metòdes publicats.¦Dobrir lo classament →¦Cap d’edicion localisada es pas encara prèsta. Los classaments revisats apareisseràn après la publicacion de las donadas.¦Classaments d’IA¦Setmana¦{{count}} entradas classadas¦{{count}} edicions publicadas¦Mes en jorn:¦Disponible tanben en¦Reng¦Nom¦Puntuacion¦Cambiaments¦Font¦Perfil¦Limitacions¦Pròvas ({{count}})¦Metòde e limitacions¦NOU¦Depaus de còde¦Editor¦Pròva independenta¦Benchmark¦Seleccion editoriala',
  fur: 'Classifiche IA¦Classifiche IA datade cun fonts e metodis publicâts.¦Cjale lis classifichis datadis, i candidâts, lis fonts e i metodis publicâts.¦Vierzi la classifiche →¦Une edizion localizade no je ancjemò pronte. Lis classifichis verificadis si mostraràn dopo la publicazion dai dâts.¦Classifiche IA¦Setemane¦{{count}} elements classificâts¦{{count}} edizions publicadis¦Inzornât:¦Disponibil ancje in¦Posizion¦Non¦Ponts¦Variazion¦Font¦Profîl¦Limitazions¦Provis ({{count}})¦Metodi e limitazions¦GNÛF¦Repository¦Editôr¦Test indipendent¦Benchmark¦Selezion editoriâl',
  sc: 'Classificas IA¦Classificas IA cun datas, fuentes y métodos publicaos.¦Esplora clasificas con fecha, candidatos, fontes y métodos publicaos.¦Abrir la clasifica →¦Entá nun hai edición traducida lista. Les clasificas revisaes apaecerán cuando se publiquen los datos.¦Classificas IA¦Selmana¦{{count}} entraes clasificaes¦{{count}} ediciones publicaes¦Anovada:¦Tamién disponible en¦Puestu¦Nome¦Puntuación¦Cambiu¦Fonte¦Perfil¦Llendes¦Pruebes ({{count}})¦Metodoloxía y llendes¦NUEVU¦Repositoriu¦Editor¦Prueba independiente¦Benchmark¦Seleición editorial',
  ast: 'Rankings d’IA¦Rankings d’IA con fecha, fontes y métodos publicaos.¦Esplora rankings con fecha, candidatos, fontes y métodos publicaos.¦Abrir el ranking →¦Entá nun hai una edición llocalizada preparada. Los rankings revisaos apaecerán cuando se publiquen los datos.¦Rankings d’IA¦Selmana¦{{count}} entraes clasificaes¦{{count}} ediciones publicaes¦Anováu:¦Tamién disponible en¦Puestu¦Nome¦Puntuación¦Cambéu¦Fonte¦Perfil¦Llimitaciones¦Pruebes ({{count}})¦Metodoloxía y llimitaciones¦NUEVU¦Repositoriu¦Editor¦Prueba independiente¦Benchmark¦Seleición editorial',
  an: 'Ranquiáns d’IA¦Ranquiáns d’IA con calendatas, fuens y métodos publicaus.¦Explora ranquiáns con calendatas, candidatos, fuens y métodos publicaus.¦Ubrir o ranquián →¦Encara no bi ha una edición localizada parada. Os ranquiáns revisaus apareixerán dimpués de publicar os datos.¦Ranquiáns d’IA¦Semana¦{{count}} entradas clasificadas¦{{count}} edicions publicadas¦Actualizau:¦Disponible tamién en¦Posición¦Nombre¦Puntuación¦Cambio¦Fuente¦Perfil¦Limitacions¦Evidencias ({{count}})¦Metodolochía y limitacions¦NUEVO¦Repositorio¦Editor¦Prueba independent¦Benchmark¦Selección editorial',
  ext: 'Rankis d’IA¦Rankis d’IA con fechas, fontes i métodos publicaos.¦Explora rankis con fechas, candidatos, fontes i métodos publicaos.¦Abril el ranki →¦Entavía no hai una edición localizá lista. Los rankis revisaos aparecerán cuando se publiquen los datos.¦Rankis d’IA¦Semana¦{{count}} entradas clasificás¦{{count}} ediciones publicás¦Actualizau:¦También disponible en¦Puestu¦Nombre¦Puntuación¦Cambio¦Fuente¦Perfil¦Limitaciones¦Pruebas ({{count}})¦Metodología y limitaciones¦NUEVU¦Repositorio¦Editor¦Prueba independiente¦Benchmark¦Selección editorial',
  vec: 'Classìfiche de l’IA¦Classìfiche de l’IA co le date, le fonti e i metodi publicài.¦Scorri classìfiche co le date, i candidati, le fonti e i metodi publicài.¦Verzi la classìfica →¦No ghe xe ancora pronta ’na edission localisada. Le classìfiche verifegàe le comparirà dopo la publicassion dei dati.¦Classìfiche de l’IA¦Settimana¦{{count}} elementi classifegài¦{{count}} edission publicàe¦Àjorna:¦Disponìbile anca in¦Posto¦Nome¦Puntejo¦Canbiamento¦Fonte¦Profilo¦Limitassion¦Prove ({{count}})¦Metodo e limitassion¦NOVO¦Repository¦Editore¦Test indipendente¦Benchmark¦Selezion editoriale',
  lij: 'Classifiche IA¦Classifiche IA co-e date, e fonti e i metodi publicæ.¦Çerca classifiche co-e date, i candidæ, e fonti e i metodi publicæ.¦Arvi a classifica →¦No gh’é ancón pronta ’na edission localizâ. E classifiche revixæ vegnan mostræ quande se publican i dæti.¦Classifiche IA¦Settimana¦{{count}} elementi classificæ¦{{count}} edission publicæ¦Agiornâ:¦Disponibile ascì in¦Posto¦Nomme¦Puntegio¦Cangiamento¦Fonte¦Profilo¦Limitassion¦Prove ({{count}})¦Metodo e limitassion¦NEUVO¦Repository¦Editô¦Test indipendente¦Benchmark¦Sceita redassionale',
  lmo: 'Classifiche IA¦Classifiche IA cun date, font e metod pubblicaa.¦Scorri classifiche cun date, candidà, font e metod pubblicaa.¦Verza la classifica →¦Gh’è no ancamò ona edizion localizzada pronta. I classificch revisionaa comparen quand i dat hinn pubblicaa.¦Classifiche IA¦Settimana¦{{count}} elementi classifichaa¦{{count}} edizion pubblicaa¦Aggiornaa:¦Disponibil anca in¦Post¦Nomm¦Puntegg¦Cambiament¦Font¦Profil¦Limitazion¦Prova ({{count}})¦Metod e limitazion¦NÖV¦Repository¦Editor¦Test indipendent¦Benchmark¦Scelta editorial',
  pms: 'Classìfiche IA¦Classìfiche IA con le date, le font e ij metod publicà.¦Sërn-a classìfiche con le date, ij candidà, le font e ij metod publicà.¦Dërv la classìfica →¦A-i é anco nen pronta n’edission localisà. Le classìfiche revisionà a-i compariran quand ij dat a saran publicà.¦Classìfiche IA¦Smana¦{{count}} element classifichà¦{{count}} edission publicà¦Agiornà:¦Disponìbil ëdcò an¦Pòst¦Nòm¦Puntagi¦Cambiament¦Font¦Profil¦Limitassion¦Prove ({{count}})¦Metod e limitassion¦NÒV¦Repository¦Editor¦Test indipendent¦Benchmark¦Sselta editorial',
  nap: 'Classifiche IA¦Classifiche IA cu date, fonti e metudi pubblicati.¦Scopri classifiche cu date, candidati, fonti e metudi pubblicati.¦Apre ’a classifica →¦Nun ce sta ancora ’na edizione localizzata pronta. ’E classifiche riviste appariranno quanno se pubblicano ’e dati.¦Classifiche IA¦Settimana¦{{count}} elementi classificati¦{{count}} edizioni pubblicate¦Aggiornato:¦Disponibile pure in¦Posto¦Nome¦Punteggio¦Cagnamiento¦Fonte¦Profilo¦Limitazioni¦Prove ({{count}})¦Metodo e limitazioni¦NOVO¦Repository¦Editore¦Test indipendente¦Benchmark¦Scelta editoriale',
  frp: 'Cllyassements d’IA¦Cllyassements d’IA datâs, avou les sôrces et les métôdes publiyês.¦Dècouvrez les cllyassements datâs, les candidats, les sôrces et les métôdes publiyês.¦Vêre lo cllyassement →¦N’y at pas d’édition locâlisêe prête por lo moment. Les cllyassements revûs paraîtront quand les données seront publiyês.¦Cllyassements d’IA¦Semena¦{{count}} entrâes cllyassêes¦{{count}} éditions publiyês¦Mîs a jorn :¦Disponiblo asse-ben en¦Rang¦Nom¦Score¦Changement¦Sôrce¦Profil¦Limites¦Preuves ({{count}})¦Métôde et limites¦NOVÊL¦Dépôt¦Éditeur¦Essai indépendant¦Benchmark¦Choix éditorial',
  gsw: 'KI-Rangliste¦Datiereti KI-Rangliste mit Quelle und veröffentlichte Methode.¦Lueg datierti Rangliste mit Kandidaten, Quelle und veröffentlichte Methode aa.¦Rangliste öffne →¦No kei übersetzti Uusgab isch parat. Prüefti Rangliste chömed, wenn d Date publiziert sind.¦KI-Rangliste¦Wuche¦{{count}} rangierti Iiträg¦{{count}} publizierti Uusgabe¦Aktualisiert:¦Au uf¦Rang¦Name¦Punkt¦Änderig¦Quelle¦Profil¦Grenze¦Beleg ({{count}})¦Methode und Grenze¦NEU¦Repository¦Verlag¦Unabhängige Test¦Benchmark¦Redaktionelli Uuswahl',
  wa: 'Ristêyes d’IA¦Ristêyes d’IA avou des dates, des sourdants eyet des metodés publiyeyes.¦Ravisez des ristêyes datêyes, leus candidats, sourdants eyet metodés publiyeyes.¦Drovi l’ristêye →¦I n’a co pont d’êdicion locålijêye prète. Les ristêyes r’loukêyes aparetront après l’publicåcion des dnêyes.¦Ristêyes d’IA¦Samwinne¦{{count}} intrêyes r’metous¦{{count}} êdicions publiyeyes¦Mî a djoû :¦Disponde avou¦Rang¦No¦Ponts¦Candjmint¦Sourdant¦Profil¦Limites¦Preuves ({{count}})¦Metode eyet limites¦NOU¦Dépôt¦Editeu¦Saye independante¦Benchmark¦Tchoes editeu',
  fy: 'AI-ranglisten¦Datearre AI-ranglisten mei boarnen en publisearre metoaden.¦Besjoch datearre ranglisten mei kandidaten, boarnen en publisearre metoaden.¦Ranglist iepenje →¦Der is noch gjin oersette útjefte klear. Besjoene ranglisten ferskine as de gegevens publisearre binne.¦AI-ranglisten¦Wike¦{{count}} ranglistitems¦{{count}} publisearre útjeften¦Bywurke:¦Ek beskikber yn¦Rang¦Namme¦Skoare¦Feroaring¦Boarne¦Profyl¦Beheiningen¦Bewiis ({{count}})¦Metoade en beheiningen¦NIJ¦Koadebewarring¦Utjouwer¦Unôfhinklike test¦Benchmark¦Redaksjonele kar',
  frr: 'AI-Ranglisten¦Datiert AI-Ranglisten mä Quellen un publizeerde Methoden.¦Kiek di datiirte Ranglisten, Kandidaten, Quellen un publizeerde Methoden an.¦Ranglist apenmaken →¦Noch is keen översetten Utgaav klaar. Pröövde Ranglisten kamen, wenn di Daten publizeert sünd.¦AI-Ranglisten¦Wek¦{{count}} rangierte Indrääg¦{{count}} publizeerde Utgaaven¦Opfrischt:¦Ook verföögbor in¦Plats¦Noom¦Punkt¦Ännerung¦Quell¦Profil¦Grenzen¦Bewies ({{count}})¦Methode un Grenzen¦NIE¦Repository¦Verlag¦Unofhängig Test¦Benchmark¦Redakschoonell Keer',
  csb: 'Rankingë AI¦Datowané rankingë AI z zdrójama ë òpublikòwaną metodą.¦Òbôczë datowané rankingë, kandydatów, zdrójë ë òpublikòwóné metodë.¦Òtemknąc ranking →¦Jesz nie je przërëchtowóné tłómaczoné wëdanié. Òcenioné rankingë òkażą sã pò òpublikòwaniu pòdôwków.¦Rankingë AI¦Tidzéń¦{{count}} pòzycji w rankingu¦{{count}} òpublikòwónëch wëdań¦Zaktualizowóné:¦Dostãpné téż w¦Môl¦Miono¦Pùnktë¦Zmiana¦Zdrój¦Profil¦Ògraniczenia¦Dowòdë ({{count}})¦Metoda ë ògraniczenia¦NOWÉ¦Repozytorium¦Wëdôwca¦Niezależny test¦Benchmark¦Wëbór redakcji',
  gag: 'AI reytingleri¦Tarixi, menbaları hem da yayımlanmış metodası olan AI reytingleri.¦Tarixli reytingleri, namzetleri, menbaları hem da yayımlanmış metodaları inceleyin.¦Reytingi aç →¦Henüz çevrilmiş baskı hazır diil. Bakılmış reytingler datalar yayımlandıktan sora görünecek.¦AI reytingleri¦Hafta¦{{count}} sıralanmış kayıt¦{{count}} yayımlanmış baskı¦Güncellendi:¦Bunuda var¦Sıra¦Ad¦Puan¦Değişiklik¦Menba¦Profil¦Sınırlamalar¦Kanıtlar ({{count}})¦Metod hem sınırlamalar¦YENİ¦Kod deposu¦Yayımcı¦Bağımsız test¦Benchmark¦Redaksiya seçimi',
  rup: 'Clasamentili IA¦Clasamentili IA cu dată, surse și metodă publicată.¦Veadeți clasamentili cu dată, candidaț, surse și metodă publicată.¦Desclide clasamentlu →¦Nu-i încă gata o ediție localizată. Clasamentili verificate se vor arăta după publicarea datelor.¦Clasamentili IA¦Săptămână¦{{count}} intrări clasate¦{{count}} ediții publicate¦Actualizat:¦Disponibil și în¦Poziție¦Nume¦Scor¦Schimbare¦Sursă¦Profil¦Limitări¦Dovezi ({{count}})¦Metodă și limitări¦NOU¦Depozit de cod¦Editor¦Test independent¦Benchmark¦Selecție editorială',
  rue: 'Рейтингуваня ШІ¦Датованы рейтингы ШІ з джерелами і опублікованыма методами.¦Перегляньте датованы рейтингы, кандидатів, джерела і опублікованы методы.¦Отворити рейтинг →¦Перекладене выданя іще не готове. Перевірены рейтингы зъявлять ся по опубліковальню даных.¦Рейтингуваня ШІ¦Тиждень¦{{count}} ранґованых записів¦{{count}} опублікованых выдань¦Оновлено:¦Доступне також по¦Місце¦Назва¦Оцїнка¦Зміна¦Джерело¦Профіль¦Обмежіня¦Докази ({{count}})¦Метод і обмежіня¦НОВЕ¦Репозиторій¦Выдавця¦Незалежный тест¦Бенчмарк¦Редакційный выбір',
  aii: 'ܕܘܪܓܐ̈ ܕܒܝܢܬܐ¦ܕܘܪܓܐ̈ ܕܒܝܢܬܐ ܥܡ ܡܒܘܥ̈ܐ ܘܐܘܪܚܐ̈ ܡܦܪܣܐ̈.¦ܚܙܘ ܕܘܪܓܐ̈ ܡܬܚܫܒܢܐ̈ ܘܡܬܚܙܝܢܐ̈ ܥܡ ܡܒܘܥ̈ܐ ܘܐܘܪܚܐ̈.¦ܦܬܚ ܕܘܪܓܐ →¦ܠܐ ܐܝܬ ܗܠܝܢ ܦܘܠܚܢܐ ܡܬܪܓܡܐ. ܕܘܪܓܐ̈ ܕܡܬܒܚܪܝܢ ܢܬܚܙܘܢ ܒܬܪ ܦܘܪܣܡܐ ܕܝܕܥܬܐ.¦ܕܘܪܓܐ̈ ܕܒܝܢܬܐ¦ܫܒܘܥܐ¦{{count}} ܡܕܥܐ̈ ܡܕܘܪܓܐ̈¦{{count}} ܦܘܠܚܢܐ̈ ܡܦܪܣܐ̈¦ܡܬܚܕܬ:¦ܐܦ ܒ¦ܕܘܪܓܐ¦ܫܡܐ¦ܢܩܘܕܐ¦ܫܘܚܠܦܐ¦ܡܒܘܥܐ¦ܦܪܘܦܝܠܐ¦ܬܚܘܡܐ̈¦ܣܗܕܘܬܐ̈ ({{count}})¦ܐܘܪܚܐ ܘܬܚܘܡܐ̈¦ܚܕܬܐ¦ܡܦܩܢܐ¦ܡܦܪܣܢܐ¦ܢܣܝܘܢܐ ܚܪܝܢܐ¦Benchmark¦ܓܒܝܬܐ ܕܡܣܕܪܢܐ',
  acy: 'تصنيفات الذكاء الاصطناعي¦تصنيفات مؤرخة للذكاء الاصطناعي مع مصادر وطرائق منشورة.¦استكشف تصنيفات مؤرخة ومرشحين ومصادر وطرائق منشورة.¦افتح التصنيف →¦لا توجد بعد نسخة محلية جاهزة. ستظهر التصنيفات المراجعة بعد نشر البيانات.¦تصنيفات الذكاء الاصطناعي¦الأسبوع¦{{count}} مدخلات مصنفة¦{{count}} إصدارات منشورة¦تم التحديث:¦متاح أيضًا بـ¦المرتبة¦الاسم¦النتيجة¦التغيير¦المصدر¦الملف¦القيود¦الأدلة ({{count}})¦المنهجية والقيود¦جديد¦مستودع¦ناشر¦اختبار مستقل¦اختبار معياري¦اختيار تحريري',
  ary: 'ترتيبات الذكاء الاصطناعي¦ترتيبات مؤرخة للذكاء الاصطناعي بمصادر ومناهج منشورة.¦اكتشف ترتيبات مؤرخة والمرشحين والمصادر والمناهج المنشورة.¦فتح الترتيب →¦ما كايناش دابا نسخة محلية واجدة. الترتيبات اللي تراجعات غادي تبان من بعد نشر البيانات.¦ترتيبات الذكاء الاصطناعي¦الأسبوع¦{{count}} عناصر مرتبة¦{{count}} إصدارات منشورة¦تحدّث:¦متاح حتى بـ¦الرتبة¦الاسم¦النقطة¦التغيير¦المصدر¦الملف¦الحدود¦الأدلة ({{count}})¦المنهجية والحدود¦جديد¦مستودع¦ناشر¦اختبار مستقل¦اختبار معياري¦اختيار تحريري',
  av: 'ГӀилман тейпазул рейтингал¦Датаялъул ва гьарурал методалъулгун гӀилман тейпазул рейтингал.¦БахӀарал рейтингал, кандидатазул, гӀаламазул ва методазул хӀакъалъулъ баян кьола.¦Рейтинг бухьи →¦Гьанже нухда хӀалтӀулеб версия гӀоло гьечӀо. ТӀаса бищарал рейтингал баян кьуралдаса нахъе лъугьина.¦ГӀилман тейпазул рейтингал¦Къоялъул къо¦{{count}} ранг кьурал материалал¦{{count}} рагӀал гьарурал версиял¦ЦӀикӀкӀана:¦Гьебго гӀелеб¦Ранг¦ЦӀар¦Натижа¦Хисизабулеб¦Баян¦Профиль¦КъагӀидал¦Далилал ({{count}})¦Метод ва къагӀидал¦ЦӀияб¦Репозитори¦Биценчи¦Гьабураб тест¦Benchmark¦Редакциялъул тӀаса бищи',
  crh: 'Yapay zekâ reytingleri¦Tarih ve menbalar ile neşir etilgen usullerge esaslanğan reytingler.¦Tarihiy reytinglerni, namzetlerni, menbalarnı ve usullerni baqıñız.¦Reytingni aç →¦Daa tercime etilgen neşir azır degil. Baqılğan reytingler malümat neşir etilgende körünecek.¦Yapay zekâ reytingleri¦Afta¦{{count}} reytingli kayıt¦{{count}} neşir etilgen san¦Yañartıldı:¦Şu tilde de bar¦Sıra¦Adı¦Netice¦Deñişme¦Menba¦Profil¦Sınırlamalar¦Deliller ({{count}})¦Usul ve sınırlamalar¦YENİ¦Kod deposı¦Neşirci¦Müstakil test¦Benchmark¦Redaksiya saylavı',
  dsb: 'AI-ranglisty¦Datowane AI-ranglisty ze žrědłami a wozjewjenymi metodami.¦Woglědajśo se datowane ranglisty, kandidaty, žrědła a wozjewjene metody.¦Ranglistu wócyniś →¦Pśełožona wudaśe hyšći njejo gótowa. Pśeglědane ranglisty se pokazuju, gaž se daty wozjawje.¦AI-ranglisty¦Tyźeń¦{{count}} zarědowane zapiski¦{{count}} wozjawjone wudaśa¦Zaktualizěrowany:¦Tež k dispoziciji w¦Městno¦Mjeno¦Bod¦Změna¦Žrědło¦Profil¦Wobgranicowanja¦Doklady ({{count}})¦Metoda a wobgranicowanja¦NOWE¦Repozitorium¦Wudawaŕ¦Niezawisny test¦Benchmark¦Wuběrk redakcije',
  fax: 'Clasificações de IA¦Clasificações de IA com datas, fontes e métodos publicados.¦Explora classificações datadas, candidatos, fontes e métodos publicados.¦Abrir classificação →¦Ainda não há uma edição localizada pronta. As classificações revistas aparecem depois da publicação dos dados.¦Classificações de IA¦Semana¦{{count}} entradas classificadas¦{{count}} edições publicadas¦Atualizado:¦Também disponível em¦Posição¦Nome¦Pontuação¦Mudança¦Fonte¦Perfil¦Limitações¦Provas ({{count}})¦Método e limitações¦NOVO¦Repositório¦Editor¦Teste independente¦Benchmark¦Escolha editorial',
  fkv: 'Tekoälyrankkaukset¦Päivätyt tekoälyrankkaukset, joilla on lähteet ja julkaistut menetelmät.¦Tutustu päivättyihin rankkauksiin, ehdokkaisiin, lähteisiin ja menetelmiin.¦Avaa rankkaus →¦Käännettyä julkaisua ei ole vielä valmiina. Tarkistetut rankkaukset näkyvät tietojen julkaisun jälkeen.¦Tekoälyrankkaukset¦Viikko¦{{count}} rankattua kohdetta¦{{count}} julkaistua numeroa¦Päivitetty:¦Saatavilla myös kielellä¦Sija¦Nimi¦Pisteet¦Muutos¦Lähde¦Profiili¦Rajoitukset¦Näyttö ({{count}})¦Menetelmä ja rajoitukset¦UUSI¦Tietovarasto¦Julkaisija¦Riippumaton testi¦Benchmark¦Toimituksellinen valinta',
  fit: 'AI-rankningar¦Daterade AI-rankningar med källor och publicerade metoder.¦Utforska daterade rankningar med kandidater, källor och metoder.¦Öppna rankningen →¦En lokaliserad utgåva är inte klar ännu. Granskade rankningar visas när uppgifterna har publicerats.¦AI-rankningar¦Vecka¦{{count}} rankade poster¦{{count}} publicerade utgåvor¦Uppdaterad:¦Även tillgänglig på¦Placering¦Namn¦Poäng¦Förändring¦Källa¦Profil¦Begränsningar¦Underlag ({{count}})¦Metod och begränsningar¦NY¦Kodarkiv¦Utgivare¦Oberoende test¦Benchmark¦Redaktionellt urval',
  gv: 'Ranglystynynynys AI¦Ranglystynynynys AI lesh eash currit as bun as nyghtynynynynynys currit.¦Jeeagh er ranglystynynynys lesh nyghtynynys, coadanyn, bunyn as oyrtyn currit.¦Fosley yn ranglyst →¦Cha nel lhieggan çhyndaait aarloo foast. Bee ranglystyn er nyn yeeagh yish yns yn fysseree currit.¦Ranglystynynynys AI¦Shiaghtin¦{{count}} recortyss rangit¦{{count}} lhiegganyn currit¦Eisht currit:¦Ry gheddyn ayns¦Rang¦Ennym¦Scóir¦Caghlaa¦Bun¦Coodaghey¦Lhimmeyrtyn¦Feanish ({{count}})¦Mod y obbyr as lhimmeyrtyn¦NOA¦Repositary¦Foillseyder¦Prove neu-chrogheydagh¦Benchmark¦Reih yn reagheyder',
  hsb: 'AI-lisćiny¦Datowane AI-lisćiny ze žórłami a wozjewjenymi metodami.¦Wobhladajće datowane lisćiny, kandidatow, žórła a wozjewjene metody.¦Lisćinu wočinić →¦Přełožene wudaće hišće njeje hotowe. Přepytane lisćiny so pokazuja po wozjewjenju datow.¦AI-lisćiny¦Tydźeń¦{{count}} zarjadowane zapiski¦{{count}} wozjewjene wudaća¦Zaktualizowane:¦Tež k dispoziciji w¦Městno¦Mjeno¦Dypk¦Změna¦Žórło¦Profil¦Wobmjezowanja¦Doklady ({{count}})¦Metoda a wobmjezowanja¦NOWE¦Repozitorium¦Wudawaŕ¦Njewotwisny test¦Benchmark¦Wuběrk redakcije',
  jct: 'Рейтинглар ИИ¦Тарихли ва манбалы, жария методикалы ИИ рейтинглары.¦Тарихли рейтингларны, намзетлерни, манбаларны ве методиканы корь.¦Рейтингни ач →¦Терджиме этильген чыгарылыш азыр дайын дегиль. Текширильген рейтинглар маълумат чыкъкач корюнир.¦Рейтинглар ИИ¦Гедже¦{{count}} рейтингли къайд¦{{count}} нешр этильген чыгарылыш¦Янартылды:¦Бу тильде де бар¦Сыра¦Ады¦Натидже¦Дегишме¦Манба¦Профиль¦Чеклер¦Далиллер ({{count}})¦Метод ве чеклер¦ЯЪЫ¦Код амбары¦Неширджи¦Мустакил тест¦Benchmark¦Редакция сайлавы',
  kdr: 'ИИ рейтинглери¦Тарихли, кайнакълы ве басылгъан усуллы ИИ рейтинглери.¦Тарихли рейтинглерни, намзетлерни, кайнакъларны ве усулларны корь.¦Рейтингни ач →¦Терджиме этильген чыкъарыш азыр даёр дегиль. Текширильген рейтинглер маълумат чыкъкъанда корюнир.¦ИИ рейтинглери¦Гедже¦{{count}} рейтингли язув¦{{count}} басылгъан чыкъарыш¦Янартылды:¦Бу тилде де бар¦Сыра¦Аты¦Балл¦Дегишме¦Кайнакъ¦Профиль¦Чеклер¦Далиллер ({{count}})¦Усул ве чеклер¦ЯЪЫ¦Код амбары¦Неширджи¦Мустакил тест¦Benchmark¦Редакция сайлавы',
  krl: 'AI-rankinguat¦Päivätyt AI-rankinguat lähtehien da julkaistujen metodien kera.¦Kaččele päivättyjä rankinguja, ehdokkaita, lähtehiä da metodeja.¦Avaa rankingua →¦Käännöstä ei ole vielä valmista. Tarkistetut rankingut näytetäh, kun tiedot julkaistah.¦AI-rankinguat¦Viikko¦{{count}} järjestettyä kohetta¦{{count}} julkaistua numeroa¦Päivitetty:¦Käytettävissä myös kielellä¦Sija¦Nimi¦Pisteet¦Muutos¦Lähde¦Profiili¦Rajoitukset¦Näytöt ({{count}})¦Metodi da rajoitukset¦UUSI¦Tietovarasto¦Julkaisija¦Riippumaton testi¦Benchmark¦Toimituksen valinta',
  kw: 'Renkys AI¦Renkys AI dedhys, gans kommynadow ha methodow embannys.¦Ke gwel renkyow dedhys, kandidatys, kommynadow ha methodow embannys.¦Ygeri an renk →¦Nyns eus unn versyon leel ready hwath. Renkys gwelys a veu diskwedhys wosa embann an data.¦Renkys AI¦Seythen¦{{count}} notenn renket¦{{count}} versyon embannys¦Nowedhys:¦Hefyd kavadow yn¦Renk¦Hanow¦Poynt¦Chanj¦Kommyn¦Profil¦Finisyow¦Pruf ({{count}})¦Method ha finisyow¦NOWYD¦Repositori kod¦Embanner¦Argerhieth anserghus¦Benchmark¦Dewis an redyoryon',
  lad: 'Classificaciones de IA¦Classificaciones de IA datadas, con fuentes y métodos publicados.¦Mira classificaciones datadas, candidatos, fuentes y métodos publicados.¦Avrir la classificacion →¦Aun no ay una edicion localizada pronta. Las classificaciones revisadas apareceran despues de publicar los datos.¦Classificaciones de IA¦Semana¦{{count}} entradas classificadas¦{{count}} ediciones publicadas¦Actualizado:¦Tambien disponible en¦Posicion¦Nombre¦Puntuacion¦Cambio¦Fuente¦Perfil¦Limitaciones¦Pruevas ({{count}})¦Metodo y limitaciones¦NUEVO¦Repositorio¦Editor¦Prueva independiente¦Benchmark¦Eleccion editorial',
  lez: 'AI рейтингар¦Датаяр, бубатIар ва кьуна методарилай AI рейтингар.¦Датаяр рейтингар, кандидатрал, бубатIар ва методарин хабар кIел.¦Рейтинг ачухь →¦Гьаниз нубатIун кьил къведач. ТIекьарна рейтингар малумат кьунал къведа.¦AI рейтингар¦Эхир¦{{count}} рангна къайд¦{{count}} кьуна гъилер¦Янгъурна:¦Амма гьелда¦Ранг¦ТIвар¦Натижа¦Гъейри¦БубатI¦Профиль¦Чекленар¦Далилар ({{count}})¦Метод ва чекленар¦ЦIийи¦Репозиторий¦Неширчи¦Гьалал тест¦Benchmark¦Редакция тIаса',
  li: 'AI-ranglieste¦Gedateerde AI-ranglieste mit bronne en gepubliceerde metodes.¦Bekiek gedateerde ranglieste mit kandidaten, bronne en metodes.¦Rangliestj opene →¦Dae is nog gein vertaalde editie gereed. Beoordeelde ranglieste versjiene na publicatie van de gegevens.¦AI-ranglieste¦Wiek¦{{count}} gerangsjikte items¦{{count}} gepubliceerde edities¦Bijgewerkt:¦Ook beschikbaar in¦Rang¦Naam¦Score¦Verandering¦Bron¦Profiel¦Beperkingen¦Bewies ({{count}})¦Methode en beperkingen¦NUJ¦Repository¦Uitgever¦Onafhankelijke test¦Benchmark¦Redactionele keuze',
  lbe: 'ИИ рейтингар¦Цlалхьун ва гьитIун методралъулгун ИИ рейтингар.¦Цlалхьун рейтингар, кандидатал, гьитIунал ва методал гьарун бачlа.¦Рейтинг тIабигь →¦Рагьун переводдалъул версия гьечlо. Тlекьаб рейтингал хъваралдаса нахъе лъугьина.¦ИИ рейтингар¦Къо¦{{count}} рейтинг кьурал материалал¦{{count}} рагlал гьарурал версиял¦Цlияб:¦Гьебго гlелеб¦Ранг¦Цlар¦Натижа¦Хисизаби¦Гьитlун¦Профиль¦Къагlидал¦Далилал ({{count}})¦Метод ва къагlидал¦Цlияб¦Репозитори¦Биценчи¦Гьабураб тест¦Benchmark¦Редакциялъул тlаса бищи',
  ku: 'Rêjeyên AI¦Rêjeyên AI yên bi dîrok, çavkanî û rêbazên weşandî.¦Rêzeyên bi dîrok, namzet, çavkanî û rêbazên weşandî bibînin.¦Rêzeyê veke →¦Hêj çapeke wergerandî amade nîne. Rêzeyên kontrolkirî piştî weşandina daneyan xuya dibin.¦Rêjeyên AI¦Hefte¦{{count}} tiştên rêzkirî¦{{count}} weşanên weşandî¦Nûkirin:¦Herwiha bi zimanê¦Cih¦Nav¦Pûan¦Guhertin¦Çavkanî¦Profîl¦Sînor¦Delîl ({{count}})¦Rêbaz û sînor¦NÛ¦Depoya kodê¦Weşanger¦Testa serbixwe¦Benchmark¦Hilbijartina edîtorî',
  mdf: 'AI рейтингть¦Ванфтома и источниконза AI рейтингть, жариянь методонь коряс.¦Ванфтома рейтингть, кандидать, источниконть ды методонь корхт.¦Рейтингть панжеме →¦Тейтерь ёмаф версия аф вал. Проверямо рейтингть кортынгак видест.¦AI рейтингть¦Недля¦{{count}} рангысь ёвтамка¦{{count}} публикациясь ёвтамка¦Поладозь:¦Кода ёвтамс¦Ранг¦Лем¦Балл¦Полавтема¦Источник¦Профиль¦Кяльхт¦Доказательства ({{count}})¦Метод ды кяльхт¦ОД¦Репозиторий¦Публикациянь теиця¦Отдельной тест¦Benchmark¦Редакциянь тӗвень',
  mwl: 'Ránquines de IA¦Ránquines de IA cun data, fuontes i métodos publicados.¦Mira ránquines con data, candidatos, fuontes i métodos publicados.¦Abrir ránquine →¦Aínda nun hai ua edición localizada lista. Os ránquines revisados aparcerán cuando se publiquen os datos.¦Ránquines de IA¦Semana¦{{count}} entradas clasificadas¦{{count}} ediciones publicadas¦Atualizado:¦Tamien disponible an¦Posición¦Nome¦Puntuación¦Mudança¦Fuonte¦Perfil¦Lhimitaciones¦Evidéncias ({{count}})¦Método i lhimitaciones¦NOVO¦Repositório¦Editor¦Teste independente¦Benchmark¦Escolha editorial',
  nds: 'KI-Ranglisten¦Dateerte KI-Ranglisten mit Born un publizeerte Methoden.¦Kiek dateerte Ranglisten mit Kandidaten, Born un publizeerte Methoden an.¦Ranglist apenmaken →¦Noch is keen översette Utgaav klaar. Pröövde Ranglisten warrt na de Publikatschoon vun de Daten wiest.¦KI-Ranglisten¦Week¦{{count}} rangierte Indrääg¦{{count}} publizeerte Utgaven¦Opfrischt:¦Ok verföögbor in¦Plats¦Naam¦Punkt¦Ännern¦Born¦Profil¦Grenzen¦Bewies ({{count}})¦Methode un Grenzen¦NIE¦Repository¦Verlag¦Unofhängig Test¦Benchmark¦Redakschoonell Utwahl',
  os: 'Искусствон технологион рейтингтæ¦Датæтимæ, истъæйтимæ æмæ æвзæрд методтимæ рейтингтæ.¦Бахæс рейтиннгтæ, кандидæттæ, истъæйтæ æмæ методтæ.¦Рейтинг фæлхæн →¦Хæрзмæ кодтой локалон нæма ис. Тæргæй рейтингтæ уыдзæн, цæмæй фыдæлдæр æрцæуынц.¦Искусствон технологион рейтингтæ¦Хафтæ¦{{count}} рæнхъы кæнæнтæ¦{{count}} æвзæрд æддæмæ¦Æнæмæ:¦Ахуыр цæйы¦Ранг¦Ном¦Балл¦Нывæнд¦Искъай¦Профиль¦Хицауджынтæ¦Дæлгæ ({{count}})¦Метод æмæ хицауджынтæ¦Нæу¦Репозиторий¦Æвзæрдтæйы¦Æркæсоны тест¦Benchmark¦Редакцион тæлхат',
  pap: 'Rankings di IA¦Rankings di IA ku fecha, fuente i método publiká.¦Mira rankings ku fecha, kandidatonan, fontenan i métodonan publiká.¦Habri e ranking →¦Ainda no tin un edishon lokalizá kla. Rankings revisá ta aparesé despues ku publiká e datonan.¦Rankings di IA¦Siman¦{{count}} entrada klasifiká¦{{count}} edishon publiká¦Aktualisá:¦Tamén disponibel na¦Posishon¦Nòmber¦Puntuashon¦Kambio¦Fuente¦Profil¦Limitashonnan¦Evidensia ({{count}})¦Método i limitashonnan¦NUEVO¦Repositorio¦Editor¦Test independiente¦Benchmark¦Selekshon editorial',
  rif: 'Tiriritin n IA¦Tiriritin n IA s ussan d izrman d yussan tssarkin.¦Ssken tiriritin, imdyan, izrman d yussan tssarkin.¦Ldi tiririt →¦Warr ila tiririt n ittarjeman. Tiriritn itwasqaden ad banen mi d ittarjeman n yisefka.¦Tiriritin n IA¦Imalas¦{{count}} n umdyan itwasqaden¦{{count}} n isuffar itwasqaden¦Itwasnqess:¦Zdat da gi¦Rrang¦Ism¦Afsar¦Abeddel¦Aɣbalu¦Aslɣu¦Ttawilat¦Tbayyin ({{count}})¦Tarrayt d ttawilat¦Amaynut¦Aɣbalu n tangalt¦Amsuffɣ¦Asekyed ilelli¦Benchmark¦Afran n umsuffɣ',
  sco: 'AI rankins¦Dated AI rankins wi sources an published methods.¦Explore dated rankins, candidates, sources an published methods.¦Open rankin →¦Nae localized edition is ready yet. Reviewed rankins will appear efter their data is published.¦AI rankins¦Week¦{{count}} rankit entries¦{{count}} published editions¦Updated:¦Available an in¦Rank¦Name¦Score¦Move¦Source¦Profile¦Limits¦Evidence ({{count}})¦Method an limits¦NEW¦Repository¦Publisher¦Independent test¦Benchmark¦Editorial choice',
  stq: 'AI-Ranglisten¦Datiierte AI-Ranglisten mäd Quellen un publizeerde Methoden.¦Bekiek datiierte Ranglisten, Kandidaten, Quellen un publizeerde Methoden.¦Ranglist apenmaken →¦Noch is neen översette Uutgaav ferree. Kontrolleerde Ranglisten wäide na Publikatsjoon fon do Daten wiesd.¦AI-Ranglisten¦Wiek¦{{count}} rangierte Indrääg¦{{count}} publizeerde Uutgaaven¦Opfriske:¦Ook verföögboar in¦Plats¦Noome¦Punkt¦Ännering¦Quell¦Profil¦Grenzen¦Bewiis ({{count}})¦Metoode un Grenzen¦NIE¦Repository¦Verlag¦Unofhängig Test¦Benchmark¦Redaksjoneele Keuze',
  tt: 'ЯИ рейтинглары¦Датасы, чыганагы һәм басылган методлары булган ЯИ рейтинглары.¦Даталы рейтингларны, кандидатларны, чыганакларны һәм методларны карагыз.¦Рейтингны ачу →¦Әлегә тәрҗемә ителгән чыгарылыш әзер түгел. Тикшерелгән рейтинглар мәгълүмат басылгач күренә.¦ЯИ рейтинглары¦Атна¦{{count}} урынга куелган язма¦{{count}} басылган чыгарылыш¦Яңартылды:¦Бу телдә дә бар¦Урын¦Исем¦Бәя¦Үзгәреш¦Чыганак¦Профиль¦Чикләүләр¦Дәлилләр ({{count}})¦Метод һәм чикләүләр¦ЯҢА¦Код саклагычы¦Бастыручы¦Бәйсез сынау¦Benchmark¦Мөхәррир сайлавы',
  tly: 'AI рейтингон¦Тарихлы AI рейтингон, манба ва нашрбу методон.¦Тарихли рейтингон, номзадон, манба ва методон бин.¦Рейтинг куш →¦Тарҷумаи нусха ҳоло тайёр ниё. Рейтингони санҷида паси нашри маълумот пайдо бин.¦AI рейтингон¦Ҳафта¦{{count}} сабти рейтингшуда¦{{count}} нашрҳои чопшуда¦Нав карда:¦Ҳамчу дастрас ба¦Ҷой¦Ном¦Баҳо¦Тағйир¦Манба¦Профил¦Маҳдудиятон¦Далилон ({{count}})¦Метод ва маҳдудиятон¦НАВ¦Анбори код¦Нашркунанда¦Санҷиши мустақил¦Benchmark¦Интихоби муҳаррир',
  udi: 'ИИ рейтингъби¦Даталъулъ, манбаъбигъ ва методбигъ гьамъи рейтингъби.¦Даталъул рейтингъби, кандидатби, манбаъби ва методби хъаб.¦Рейтинг хъаб →¦Таржума эдизия афчуд гьечI. Текьар рейтингъби маълумат чIайилъ гъач.¦ИИ рейтингъби¦Хафта¦{{count}} рейтинг эциъул къайдби¦{{count}} чIайитIэдизия¦Къайтан:¦Гьеб гъабза¦Ранг¦ЦIар¦Натижа¦Къайтан¦Манба¦Профиль¦Чекленар¦Далилби ({{count}})¦Метод ва чекленар¦ЦIийи¦Код репозиторий¦Неширчи¦Мустакъил тест¦Benchmark¦Редакция къарай',
  yec: 'AI-Rangliste¦Datiert AI-Rangliste mit Quelle un publizierte Methode.¦Lies datiierte Rangliste mit Kandidat, Quelle un publizierte Methode.¦Rangliste uftue →¦No kei übersetzti Uusgab isch parat. Prüefti Rangliste erschined nach dr Publikation vo de Date.¦AI-Rangliste¦Wuche¦{{count}} rangierti Iiträg¦{{count}} publizierti Uusgabe¦Aktualisiert:¦Au uf¦Rang¦Name¦Punkt¦Änderig¦Quelle¦Profil¦Grenze¦Beleg ({{count}})¦Methode und Grenze¦NEU¦Repository¦Verlag¦Unabhängige Test¦Benchmark¦Redaktionelli Uuswahl',
  zgh: 'ⵉⵙⵎⵉⵍⵏ ⵏ ⵜⵉⵣⵉⴳⵣⵜ ⵜⴰⵎⴰⵙⵙⴰⵏⵜ¦ⵉⵙⵎⵉⵍⵏ ⵉⵣⵔⵉⵏ ⵙ ⵉⵙⵖⵣⴰⵏ ⴷ ⵜⵉⵎⵙⴽⴰⵔ ⵉⵙⵙⵓⴼⵖⵏ.¦ⵙⵙⵏⵎⵍ ⵉⵙⵎⵉⵍⵏ ⵉⵣⵔⵉⵏ, ⵉⵙⵙⵏⴽⴰⴷⵏ, ⵉⵙⵖⵣⴰⵏ ⴷ ⵜⵉⵎⵙⴽⴰⵔ.¦ⵙⵙⵏ ⴰⵙⵎⵉⵍ →¦ⵓⵔ ⵜⵍⵍⵉ ⵜⵓⵙⵙⵓⵔⵜ ⵜⵙⵓⵖⵍⵜ ⵜⵙⵙⴼⵍⵏ. ⴰⴷ ⴷⵓⵔⵏ ⵉⵙⵎⵉⵍⵏ ⵎⴱⵍ ⵜⵙⵙⵓⴼⵖⵜ ⵏ ⵉⵙⴼⴽⴰ.¦ⵉⵙⵎⵉⵍⵏ ⵏ IA¦ⴰⵎⴰⵍ¦{{count}} ⵉⵙⴽⴰⵏ ⵉⵙⵎⵍⵏ¦{{count}} ⵜⵙⵙⵓⴼⵖⵉⵏ¦ⵉⵜⵜⵓⵙⵙⵓⴼⵖ:¦ⵉⵍⵍⴰ ⴰⵡⴷ ⴳ¦ⴰⵙⵎⵉⵍ¦ⵉⵙⵎ¦ⴰⵙⵏⴼⴰⵍ¦ⴰⵙⵏⴼⴰⵍ¦ⵉⵙⵖⵣ¦ⴰⵙⵏⴼⴰⵍ¦ⵉⵍⵉⵎⵉⵜⵏ¦ⵜⵓⵙⵉⴷⵉⵏ ({{count}})¦ⵜⴰⵎⴰⵙⵙⴰⵏⵜ ⴷ ⵜⵓⵙⵉⴷⵉⵏ¦ⴰⵎⴰⵢⵏⵓ¦ⴰⵏⴱⴰⵔ¦ⴰⵎⵙⵙⵓⴼⵖ¦ⴰⵙⵏⵎⵙⴰⵢ¦Benchmark¦ⴰⴼⵔⴰⵏ ⴰⵎⵙⵙⵉⵡⵍ',
} as const;

type TranslationKey = keyof typeof TRANSLATIONS;
const translationEntries = Object.entries(TRANSLATIONS).map(([key, row]) => {
  const values = row.split('¦');
  if (values.length !== MESSAGE_KEYS.length) {
    throw new Error(`La traduction de classement « ${key} » contient ${values.length} champs.`);
  }
  return [
    key,
    Object.fromEntries(MESSAGE_KEYS.map((messageKey, index) => [messageKey, values[index]])),
  ];
});
const parsedTranslations = Object.fromEntries(translationEntries) as Record<
  TranslationKey,
  RankingMessageValues
>;

export interface RankingMessages extends RankingMessageValues {
  /** Locale du texte renvoyé ; différente de la locale demandée en cas de repli. */
  sourceLocale: string;
}

const SOURCE_LOCALES: Record<TranslationKey, string> = {
  en: 'en',
  fr: 'fr-FR',
  bg: 'bg-BG',
  hr: 'hr-HR',
  cs: 'cs-CZ',
  da: 'da-DK',
  nl: 'nl-NL',
  et: 'et-EE',
  fi: 'fi-FI',
  de: 'de-DE',
  el: 'el-GR',
  hu: 'hu-HU',
  ga: 'ga-IE',
  it: 'it-IT',
  lv: 'lv-LV',
  lt: 'lt-LT',
  mt: 'mt-MT',
  pl: 'pl-PL',
  pt: 'pt-PT',
  ro: 'ro-RO',
  sk: 'sk-SK',
  sl: 'sl-SI',
  es: 'es-ES',
  sv: 'sv-SE',
  sq: 'sq-AL',
  be: 'be-BY',
  bs: 'bs-BA',
  is: 'is-IS',
  mk: 'mk-MK',
  nb: 'nb-NO',
  nn: 'nn-NO',
  ru: 'ru-RU',
  'sr-cyrl': 'sr-Cyrl-RS',
  'sr-latn': 'sr-Latn-RS',
  uk: 'uk-UA',
  tr: 'tr-TR',
  hy: 'hy-AM',
  az: 'az-AZ',
  ka: 'ka-GE',
  lb: 'lb-LU',
  ca: 'ca-ES',
  eu: 'eu-ES',
  gl: 'gl-ES',
  cy: 'cy-GB',
  gd: 'gd-GB',
  fo: 'fo-FO',
  rm: 'rm-CH',
  se: 'se-NO',
  sma: 'sma-NO',
  smj: 'smj-SE',
  smn: 'smn-FI',
  sms: 'sms-FI',
  yi: 'yi',
  rom: 'rom',
  br: 'br-FR',
  co: 'co-FR',
  oc: 'oc-FR',
  fur: 'fur-IT',
  sc: 'sc-IT',
  ast: 'ast-ES',
  an: 'an-ES',
  ext: 'ext-ES',
  vec: 'vec-IT',
  lij: 'lij-IT',
  lmo: 'lmo-IT',
  pms: 'pms-IT',
  nap: 'nap-IT',
  frp: 'frp-FR',
  gsw: 'gsw-CH',
  wa: 'wa-BE',
  fy: 'fy-NL',
  frr: 'frr-DE',
  csb: 'csb-PL',
  gag: 'gag-MD',
  rup: 'rup-RO',
  rue: 'rue-UA',
  aii: 'aii-AM',
  acy: 'acy-CY',
  ary: 'ary-ES',
  av: 'av-RU',
  crh: 'crh-UA',
  dsb: 'dsb-DE',
  fax: 'fax-ES',
  fkv: 'fkv-NO',
  fit: 'fit-SE',
  gv: 'gv-IM',
  hsb: 'hsb-DE',
  jct: 'jct-UA',
  kdr: 'kdr-PL',
  krl: 'krl-FI',
  kw: 'kw-GB',
  lad: 'lad-BA',
  lez: 'lez-RU',
  li: 'li-NL',
  lbe: 'lbe-RU',
  ku: 'ku-AM',
  mdf: 'mdf-RU',
  mwl: 'mwl-PT',
  nds: 'nds-DE',
  os: 'os-GE',
  pap: 'pap-CW',
  rif: 'rif-ES',
  sco: 'sco-GB',
  stq: 'stq-DE',
  tt: 'tt-FI',
  tly: 'tly-AZ',
  udi: 'udi-AZ',
  yec: 'yec-CH',
  zgh: 'zgh-MA',
};

export const RANKING_UI_TRANSLATION_LOCALES = Object.values(SOURCE_LOCALES);

/**
 * Les variantes régionales réutilisent la traduction de leur langue. Le repli anglais est
 * explicite pour que l'interface puisse signaler la langue réelle de ses libellés.
 */
export function rankingMessages(locale: string): RankingMessages {
  const parsed = new Intl.Locale(locale);
  const scriptKey = parsed.script ? `${parsed.language}-${parsed.script}`.toLowerCase() : undefined;
  const key: TranslationKey =
    (scriptKey && scriptKey in parsedTranslations ? (scriptKey as TranslationKey) : undefined) ??
    (parsed.language in parsedTranslations ? (parsed.language as TranslationKey) : 'en');
  return { ...parsedTranslations[key], sourceLocale: SOURCE_LOCALES[key] };
}

export function hasRankingUiTranslation(locale: string): boolean {
  const requested = new Intl.Locale(locale);
  const copy = rankingMessages(locale);
  return copy.sourceLocale !== 'en' || requested.language === 'en';
}

export function formatRankingCount(template: string, count: number, locale: string): string {
  const number = new Intl.NumberFormat(locale).format(count);
  if (template.startsWith('{{count}} ')) {
    return `${template.slice('{{count}}'.length).trim()}: ${number}`;
  }
  return template.replace('{{count}}', number);
}
